class credential:
  def __init__(self
              ,s3_bing_news_raw
              ,s3_bing_news_cleaned
              ,s3_google_news_raw
              ,s3_google_news_cleaned
              ,s3_news_api_raw
              ,s3_news_api_cleaned
              ,s3_news_catcher_raw
              ,s3_news_catcher_cleaned
              ,s3_ny_times_raw
              ,s3_ny_times_cleaned
              ,s3_poltifiact_raw
              ,s3_Ngram
              ,credential_google_key
              ,credential_news_catcher_key
              ,credential_news_api_key
              ,credential_NYTimes_key
              ,credential_Bing_key
              ,credential_aws_key
              ,credential_aws_secret):
    self.s3_bing_news_raw=s3_bing_news_raw
    self.s3_bing_news_cleaned=s3_bing_news_cleaned
    self.s3_google_news_raw=s3_google_news_raw
    self.s3_google_news_cleaned=s3_google_news_cleaned
    self.s3_news_api_raw=s3_news_api_raw
    self.s3_news_api_cleaned=s3_news_api_cleaned
    self.s3_news_catcher_raw=s3_news_catcher_raw
    self.s3_news_catcher_cleaned=s3_news_catcher_cleaned
    self.s3_ny_times_raw=s3_ny_times_raw
    self.s3_ny_times_cleaned=s3_ny_times_cleaned
    self.s3_poltifiact_raw=s3_poltifiact_raw
    self.s3_Ngram=s3_Ngram
    self.credential_google_key=credential_google_key
    self.credential_news_catcher_key=credential_news_catcher_key
    self.credential_news_api_key=credential_news_api_key
    self.credential_NYTimes_key=credential_NYTimes_key
    self.credential_Bing_key=credential_Bing_key
    self.credential_aws_key=credential_aws_key
    self.credential_aws_secret=credential_aws_secret